# This is the initial test keys dictionary for APOGEE
#
KeysDictionary("apogee", (0,2), *(
    # misc
    Key("text", String(), help="text for humans"),
    Key("version", String(), help="version string derived from svn info."),
    
    # ICC Keywords
    Key('exposureState',
        Enum('READING','INTEGRATING','PROCESSING','DONE','ABORTING','ABORTED','UTR', name="state"),
        Float(name="time", help="esimated total time for this state; 0 if too short to bother with a countdown timer", units="sec"),
        Float(name="time_left", help="esimated remaining time for this state; 0 if too short to bother with a countdown timer", units="sec"),
#        Int(name="UTR_counter", help="Counter of just completed UTR read; 0 for the any state other than UTR", units="read"),
        help='The current state of the exposure and associated timings.'),
    Key('exposureWroteFile',
        String(name="wrotefile"),
        help="Name of FITS file just written to disk"),
    Key('exposureMode',
        Enum('fowler','sutr',),
        Float(name="nfowler", help="number of fowler samples or Up-the-Ramp frames to take"),
        help="number of fowler samples"),

    # Spectrograph Setup/Status Keywords
    Key('arrayPower',
        Enum('ON','OFF','?'),
        help='Status of controller array power'),
    Key('dspload',
        String(),
        help='Name of DSP file currently in use'),
    Key('dspFiles',
        String()*(0,10),
        help='List of available DSP files'),

    # Collimator Tip/Tilt/Focus Keywords
    Key('collOrient',
        Float(name="piston", units="microns", help="+ brings collimator towards the instrument"),
        Float(name="pitch", units="pixels", help="+ tips the beam down"),
        Float(name="yaw", units="pixels", help="+ tips the beam to the right as seen by the collimator"),
        help='Collimator orientation'),
    Key('collMountPos',
        Float(units='microns')*3,
        help='Current collimator actuator position'),
    Key('collMountLimits',
        Float(units='microns')*2,
        help='Low, high software limits for collimator actuator position'),
    Key("collLimitSwitch",
        Bool("false", "true")*6,
        help="home1, forward1, home2, forward2, home3, forward3 limit switch activated?"),
    Key('collIndexer',
        Bool('Off', 'On'),
        help='Is the collimator controller available (on and communicating)?'),

    # Detector Dither Keywords
    Key('ditherPosition',
        Float(units='pixels'),
        help='Current dither position'),
    Key('ditherLimits',
        Float(units='pixels')*2,
        help='Low, high software limits for dither position'),
    Key("ditherLimitSwitch",
        Bool("false", "true")*2,
        help="Home, forward dither limit switch activated?"),
    Key('ditherIndexer',
        Bool('Off', 'On'),
        help='Is the dither controller available (on and communicating)?'),

    # Instrument Keywords
    Key('tempNames', 
        String()*20,
        help='Location name of each temperature sensor'),
    Key('temps', 
        Float(units='K')*20,
        help='temperatures inside apogee'),
    Key('tempInterval', 
        Float(units='sec'),
        help='Reporting interval of the temperatures and alarms; 0.0 turns automatic reporting off'),
    Key('tempAlarms', 
        Bool("0", "1")*20,
        help='Alarm status for each temperature sensor; 0=ok, 1=alarm'),
    Key('tempThresholds', 
        Float(units='K')*20,
        help='Threshold for each sensor (degreesK)'),
    Key('tempMin', 
        Float(units='K')*20,
        help='Expected minimum values (degreesK)'),
    Key('tempMax', 
        Float(units='K')*20,
        help='Expected maximum values (degreesK)'),
    Key('vacuum', 
        Float(units='Torr'),
        help='Current vacumm; NaN if not available (Torr)'),
    Key('vacuumInterval', 
        Float(units='sec'),
        help='Reporting interval of the vacuum and alarms; 0.0 turns automatic reporting off'),
    Key('vacuumAlarm', 
        Bool("0", "1"),
        help='Vacuum Alarm state; 0=ok, 1=alarm'),
    Key('vacuumThreshold', 
        Float(units='Torr'),
        help='Vacuum Threshold'),
    Key('vacuumLimits', 
        Float(units='Torr')*2,
        help='Expected Low, High Vacuum'),
    Key('ln2Level', 
        Float(units='%'),
        help='Current level of LN2 in instrument; NaN if not available'),
    Key('ln2Interval', 
        Float(units='sec'),
        help='Reporting interval of the LN2 level and alarms; 0.0 turns automatic reporting off'),
    Key('ln2Alarm', 
        Bool("0", "1"),
        help='LN2 Level Alarm state; 0=ok, 1=alarm'),
    Key('ln2Threshold', 
        Float(units='%'),
        help='LN2 Level below which an Alarm is triggered'),
    Key('ln2Limits', 
        Float(units='%')*2,
        help='Expected Low, High LN2 level'),

))
