KeysDictionary('cmds',(2,0),
    Key('cmdDone',UInt(),help='Hub internal command sequence number'),
    Key('newCmd',UInt(),help='Hub internal command sequence number'),
    Key('cmdTime',Double(),units='s',help='MJD UTC timestamp'),
    Key('cmdr',String(),help='Commander name'),
    Key('cmdrMID',UInt(),help='Hub internal'),
    Key('cmdrCID',String(),help='Deprecated hub internal'),
    Key('cmdActor',String(),help="Name of actor handling command"),
    Key('cmdText',String(),help="The command text"),
    Key('cmdQueued',
        UInt(name='hubID', help='Internal command sequence number. Unique within a run of the hub'),
        Double(name='cmdTime',units='s',help='MJD TAI timestamp'),
        String(name='cmdr',help='Commander name'),
        UInt(name='cmdrMID',help='The sequence number from the commander'),
        String(name='actor',help='Actor name'),
        UInt(name='actorMID',help='The sequence number assigned to the command sent to the actor'),
        String(name='cmdText',help='The command text'),
        doCache=False,
        help='Generated right before a new command is sent to an actor.')
)
