KeysDictionary('gcamera', (1, 0),
    Key("text", String(help="text for humans")),
    Key("version", String(help="EUPS/SVN version")),
    Key("simulating", 
       Bool('Off', 'On', help="Are we reading simulated/historical data, or taking new images?"),
       String(help="directory from which simulations are reading data."),
       Int(help="sequence number of the last read image")),
    Key("exposureState", 
       Enum('idle','integrating','reading','done','aborted','failed'),
       Float(help="remaining time for this state (0 if none, short or unknown)", units="sec"),
       Float(help="total time for this state (0 if none, short or unknown)", units="sec")),
    Key("filename", 
       String(help='last read file')),
    Key("cooler",
        Float(name="setpoint", help="CCD temperature setpoint", units="degC"),
        Float(name="ccdTemp", help="CCD temperature reported by the camera", units="degC"),
        Float(name="heatsinkTemp", help="Heatsink temperature reported by the camera", units="degC"),
        Float(name="coolerLoad", help="Load on the cooler", units="percent"),
        Int(name="fanStatus", help="Fan status. Always 1 with this camera (camera has no fan)."),
        Enum('Off', 'RampingToSetPoint', 'Correcting', 'RampingToAmbient', 'AtAmbient', 'AtMax', 'AtMin', 'AtSetPoint', 'Invalid',
             name="coolerStatus",
             help="Cooler status. Correcting appears to be the normal state, All others should be considered bad. AtSetPoint does not appear to occur.")),
    Key("binning",
        Int(name="vertical",help="Binned vertical pixels.",units="pixels"),
        Int(name="horizontal",help="Binned horizontal pixels.",units="pixels")),
    Key("cameraConnected", Bool('True','False',help="Is the camera responsive?")),
    Key("dataDir",String(help="Directory where guider images are currently being written.")),
    Key("nextSeqno",Int(help="Image number of currently active guider image.")),
    Key("flatCartridge",String(help="Cartridge number for current guider image.")),
    Key("darkFile",String(help="Location of FITS file containing current dark frame.")),
    Key("flatFile",String(help="Location of FITS file containing current flat frame.")),
    Key("stack", Int(help="Number of integrations to stack for a single exposure.")),
)

