KeysDictionary("piezomirror", (1,0), *(

######## Keys specific to mirror with piezos ##################
# note: should piezo units be steps rather than microsteps?
    Key("piezoStatus",
        Int(invalid = "NaN"),
        help = "1: piezo correction task halted. 2: piezo correction pause requested. 3: piezo corrections disabled",
    ),
    Key("piezoCorr",
        Float(units="microsteps", invalid="NaN")*3,
        help = "piezo Corrections (microsteps)",
    ),
    # piezo-specific parameters returned from XQ#SHOWPAR
    Key("piezoMaxPos",
        Float(units="microsteps"),
        help = "Max piezo postion (microsteps)",
    ),
    Key("piezoMinPos",
        Float(units="microsteps"),
        help = "Min piezo postion (microsteps)",
    ),
    Key("piezoNSteps",
        Int(),
        help = "number of steps of piezo position",
    ),
    Key("piezoResolution",
        Int(units="microsteps/piezo ctrl bit"),
        help = "resolution (microsteps/piezo ctrl bit)"
    ),

######## Keys shared by all mirrors #####################
    Key("text",
        String(),
        help = "Text message",
    ),
    Key("yourUserID",
        Int(),
        help = "Your user ID number; use this to recognize replies triggered by your commands; never 0",
    ),
    Key("numUsers",
        Int(),
        help = "Number of connected users",
    ),
    Key("userInfo",
        Int(name="id", help = "user ID"),
        String(name="address", help = "socket address"),
        help = "Basic information about one user",
    ),
    Key("unknownCommand",
        String(help = "command verb"),
        help = "The command verb (the first word of your command string) is not supported by this actor",
    ),
    Key("version",
        String(invalid="?"),
        help = "The version of the actor",
    ),
    Key("refCount",
        Int(name="refCount", help = "refcount"),
        String(name="object", help = "object"),
        help = "The reference count for an object",
    ),
    Key("galilConState", 
        Enum("Connecting", "Authorizing", "Connected", 
            "Disconnecting", "Disconnected", "Failing", "Failed",
            name="state",
            help = "Connection State"
        ),
        String(name="reason", help = "Reason"),
        help =  "State of connection to the dev hardware controller. State is one of Connecting, Authorizing, Connected, Disconnecting, Failing, Disconnected or Failed (the states of an RO.Comm.TCPConnection object). <i>Reason</i> is the reason it got to this state ('' if no reason specified), Note: Dev is a placeholder for a device name",
    ),
#     Key("superseded", help = "The command was superseded by some other command"),
#     Key("timeout", help = "The command timed out"),

    Key("desOrient",
        Float(name="piston",help="piston", units="um", invalid="NaN"),
        Float(name="xTilt", help="x tilt", units="arcsec", invalid="NaN"),
        Float(name="yTilt", help="y tilt", units="arcsec", invalid="NaN"),
        Float(name="xTransl", help="x translation", units="um", invalid="NaN"),
        Float(name="yTransl", help="y translation", units="um", invalid="NaN"),
        Float(name="zRotate", help="z rotation", units="arcsec", invalid="NaN"),
        help = "desired mirror orientation",
    ),
    Key("desOrientAge",
        Float(units = "seconds", invalid="NaN"),
        help = "Elapsed time since a desired orientation was set",
    ),
    Key("cmdMount",
        Float(units="steps", invalid="NaN") * (3,5),
        help = "Commanded mount positions",
    ),
    Key("cmd",
        String(name = "cmdVerb"),
        help = "Current command (verb) executing",
    ),
    Key("maxDuration",
        Float(units = "seconds", invalid="NaN"),
        help = "Maximum amount of time expected for current process",
    ),
    Key("duration",
        Float(units = "seconds", invalid="NaN"),
        help =  "Time spent executing so far",
    ),
    Key("orient",
        Float(name="piston", help="piston", units="um", invalid="NaN"),
        Float(name="xTilt", help="x tilt", units="arcsec", invalid="NaN"),
        Float(name="yTilt", help="y tilt", units="arcsec", invalid="NaN"),
        Float(name="xTransl", help="x translation", units="um", invalid="NaN"),
        Float(name="yTransl", help="y translation", units="um", invalid="NaN"),
        Float(name="zRotate", help="z rotation", units="arcsec", invalid="NaN"),
        help = "desired mirror orientation",
    ),
    Key("actMount",
        Float(units = "steps", invalid="NaN") * (3,5),
        help = "Measured actuator mount positions, if there are encoders, else commanded actuator mount position",
    ),
    Key("encMount",
        Float(units = "steps", invalid="NaN") * (3,5),
        help = "The measured or actual encoder mount positions",
    ),
    Key("iter",
        UInt(invalid="NaN"),
        help = "Current move iteration"
    ),
    Key("axisHomed",
        Bool('0', '1') * (3,5),
        help = "Axes that are homed",
    ),
    Key("status",
        Bits('stopcode:8', 'statusword:24') * (3,5), # should we breakdown status word into individual bits?
        help = "see http://www.apo.nmsu.edu/Telescopes/HardwareControllers/GalilMirrorControllers.html#StatusWord",
    ),
    Key("maxIter",
        UInt(),
        help = "Maximum allowed iterations for a move",
    ),
    Key("homing",
        Bool('0', '1', invalid="?") * (3,5),
        help = "Axes that are currently homing",
    ),
    Key("unparsedReply",
        String(),
        help = "This Galil reply could not be parsed and so is being ignored",
    ),
    Key("unknownReplyKey",
        String(name="key", help="data key"),
        String(name="data", help="data"),
        String(name="reply", help="full reply"),
        help = "One item of Galil data had an unrecognized key",
    ),
    Key("badGalilReply",
        String(),
        help = "Parsed Galil reply that confused the actor",
    ),
    Key("galilSoftwareVersion",
        String(),
        help = "Software Version on Galil",
    ),
    Key("deviceSoftwareVersion",
        String(),
        help = "Software version for additional device-specific code",
    ),
    Key("galilNAXES",
        Int(),
        help = "Number of axes (1-6). Note: 3.5m M3 mirror has 6 axes, although only 3 may be used",
    ),
    Key("galilDOAUX",
        Int(),
        help = "If nonzero, status info emitted from aux serial port",
    ),
    Key("galilMOFF",
        Int(),
        help = "Turn off all motors after each move, if nonzero",
    ),
    Key("galilNCORR",
        Int(),
        help = "Number of encoder-based corrections after each move",
    ),
    Key("galilWTIME",
        Float(units = "seconds"),
        help = "Settling time after a move",
    ),
    Key("galilENCTIME",
        Float(units = "seconds"),
        help = "Settling time after a move and after WTIME, before encoders are read",
    ),
    Key("galilLSTIME",
        Float(units = "seconds"),
        help = "Max time required to back out of a limit at low speed",
    ),
    Key("galilHalfRNG",
        Int(units="microsteps") * (3,5),
        help = "Half the range of motion",
    ),
    Key("galilSPD",
        Int(units="microsteps/sec") * (3,5),
        help = "Max speed",
    ),
    Key("galilHMSPD",
        Int(units="microsteps/sec") * (3,5),
        help = "Max speed for finding home switch",
    ),
    Key("galilACC",
        Int(units="microsteps/sec^2") * (3,5),
        help = "Maximum acceleration and deceleration of each axis",
    ),
    Key("galilMINCORR",
        Int(units="microsteps") * (3,5),
        help = "The mininimum error that will be corrected, 0 means correct any error",
    ),
    Key("galilMAXCORR",
        Int(units="microsteps") * (3,5),
        help = "The max error that will be corrected at the end of a move. Set to 0 if no encoder or no correction is desired",
    ),
    Key("galilST_FS",
        Int(units="microsteps/full step") * (3,5),
        help = "Step resolution; 1 for a servo motor",
    ),
    Key("galilMARG",
        Int(units="microsteps") * (3,5),
        help = "Margin between the hard and soft reverse limits",
    ),
    Key("galilINDSEP",
        Int(units="microsteps") * (3,5),
        help = "If this axis has an index pulse encoder and it is used for homing, then set to the separation between index pulses",
    ),
    Key("galilENCRES",
        Float(units="ticks/microstep") * (3,5),
        help = "Resolution of encremental auxiliary encoder; 0 if no encoder",
    ),
))
