KeysDictionary("platedb", (1,2),
    Key("activePlugging",
        Int(name="cartridge", help="The cartridge in use", invalid=-1),
        Int(name="plate", help="The plate ID", invalid=-1),
        String(name="pointing", help="The active pointing", invalid="?"),
        Float(name="ra", help="The plate centre's right ascension"),
        Float(name="dec", help="The plate centre's declination"),
        Float(name="hour_angle", help="The hour_angle the plate was drilled for"),
        Float(name="temperature", help="The temperature the plate was drilled for"),
        help="The currently-mounted cartridge's properties",
    ),
    Key("gprobe",
        Int(name="cartridgeId", help="The cartridge the gprobe belongs to"),
        Int(name="gprobeId", help="The gprobe ID"),
        Bool("False", "True", name="enables", help="Does this cartridge have this gprobe?"),
        Float(name="rotation", units="degrees", help="+CCW, image Y to plate N"),
        Float(name="focusOffset", units="microns", help="+ve towards sky,(inside focus probes)"),
        help="The properties of a spectroscopic guide probe",
    ),
    Key("gprobesInUse",
        String(name="gprobes", help="+CCW, image Y to plate N")*(0,),
        help="A list of (id=bool) values for all this cartridge's gprobes telling us if they are expected to be used for this pointing",
    ),
    Key("pointingInfo",
        Int(name="plate", help="The plate ID", invalid=-1),
        Int(name="cartridge", help="The cartridge in use", invalid=-1),
        String(name="pointing", help="The active pointing", invalid="?"),
        Float(name="ra", help="The plate centre's right ascension"),
        Float(name="dec", help="The plate centre's declination"),
        Float(name="hour_angle", help="The hour_angle the plate was drilled for"),
        Float(name="temperature", help="The temperature the plate was drilled for"),
        Float(name="lambda", help="The wavelength the plate was designed for"),
        help="The currently loaded plate",
    ),
)
