# Based on the TCC keywords documented at (with guide camera keywords omitted):
# http://www.apo.nmsu.edu/Telescopes/TCC/MessageKeywords.html

KeysDictionary("tcc", (3, 8),
    Key("airTemp", Float(invalid="NaN", units="C"), help="Temperature of the outside air. Used for refraction correction."),
    Key("axePos", Float(invalid="NaN", units="deg", help="Order is Az, Alt, Rot")*3, help=
        """Actual mount position of azimuth, altitude and instrument rotator, as reported by
        the axes controllers. Not many digits past the decimal but very useful for status displays."""
    ),
    Key("altDTime", Float(invalid="NaN", units="s")),
    Key("altErr", Float(invalid="NaN", units="as")*3, doCache=False),
    Key("altLim", Float(invalid="NaN", units="deg")*2, Float(invalid="NaN", units="deg/s"),
        Float(invalid="NaN", units="deg/s^2"), Float(invalid="NaN", units="deg/s^3")),
    Key("altMSStat", Float(invalid="NaN", units="as")*2, String()),
    Key("altPosRejected", Float(invalid="NaN", units="deg")*3, doCache=False),
    Key("altStat", Float(invalid="NaN", units="deg"), Float(invalid="NaN", units="deg/s"),
        Double(invalid="NaN", units="s"), UInt(invalid="NaN", reprFmt = '0x%x')),
    Key("axisBadStatusMask", UInt(invalid="NaN", reprFmt = '0x%x')),
    Key("axisCmdState", Enum("Drifting", "Halted", "Halting", "Slewing", "Tracking", "NotAvailable", invalid="?")*3),
    Key("axisErrCode", String(invalid="?")*3),
    Key("axisHighAccel"),
    Key("axisInit", String(), doCache=False),
    Key("axisMaxDTime", Float(invalid="NaN", units="s"), doCache=False),
    Key("axisNoSlew", String(), doCache=False),
    Key("axisNoTrack", String(), doCache=False),
    Key("axisStop", String(), doCache=False),
    Key("axisWarnStatusMask", UInt(invalid="NaN", reprFmt = '0x%x')),
    Key("azAltDist", Float(invalid="NaN"), doCache=False),
    Key("azDTime", Float(invalid="NaN", units="s")),
    Key("azErr", Float(invalid="NaN", units="as")*3, doCache=False),
    Key("azLim", Float(invalid="NaN", units="deg")*2, Float(invalid="NaN", units="deg/s"),
        Float(invalid="NaN", units="deg/s^2"), Float(invalid="NaN", units="deg/s^3")),
    Key("azMSStat", Float(invalid="NaN", units="as")*2, String()),
    Key("azPosRejected", Float(invalid="NaN", units="deg")*3, doCache=False),
    Key("azStat", Float(invalid="NaN", units="deg"), Float(invalid="NaN", units="deg/s"),
        Double(invalid="NaN", units="s"), UInt(invalid="NaN", reprFmt = '0x%x')),
    Key("azWrapPref", Enum("None", "Nearest", "Negative", "Middle", "Positive", "NoUnwrap"), doCache=False),
    Key("badAltDTime"),
    Key("badAltStatus"),
    Key("badAzDTime"),
    Key("badAzStatus"),
    Key("badCmd"),
    Key("badRotDTime"),
    Key("badRotStatus"),
    Key("badUser", UInt(invalid="NaN"), doCache=False),
    Key("blockInfo", String(), UInt(invalid="NaN")*2, doCache=False),
    Key("boresight", PVT(), PVT()),
    Key("broadcast", String(), doCache=False),
    Key("calibOff", PVT(), PVT(), PVT()),
    Key("cmd", String(), doCache=False),
    Key("cmdDTime", Float(invalid="NaN", units="s"), doCache=False),
    Key("convAng", PVT(), doCache=False),
    Key("convPM", Float(invalid="NaN", units="as/century")*2, Float(invalid="NaN", units="as"),
        Float(invalid="NaN", units="km/s"), doCache=False),
    Key("convPos", PVT(), PVT(), doCache=False),
    Key("currArcOff", PVT(), PVT()),
    Key("currGCFilt"),
    Key("currUsers", UInt(invalid="NaN")),
    Key("deadProc", String()*(1,), doCache=False),
    Key("disabledProc", String()*(1,), doCache=False),
    Key("duration", Float(invalid="NaN", units="s"), doCache=False),
    Key("eText", String(), doCache=False),
    Key("expTime", Float(invalid="NaN", units="s"), doCache=False),
    Key("expected", String(), doCache=False),
    Key("facil", String(), doCache=False),
    Key("failed"),
    Key("flushedFromBox", String(), doCache=False),
    Key("gBinFactor", Int(invalid="NaN"), Int(invalid="NaN")),
    Key("gBoxSize", Float(invalid="NaN"), Float(invalid="NaN")),
    Key("gCamBusy"),
    Key("gCamCmd", String()),
    Key("gCamID", Int(invalid="NaN"), Int(invalid="NaN")),
    Key("gCamInfo", String(), Float(invalid="NaN"), Float(invalid="NaN"), Int(invalid="NaN")),
    Key("gCamReply", String()),
    Key("gcFilt", Int(invalid="NaN"), String(), Float(invalid="NaN"), Float(invalid="NaN"), Float(invalid="NaN"), Float(invalid="NaN")),
    Key("gcFocus", Float(invalid="NaN", units="um")),
    Key("gcNFilt", Int(invalid="NaN")),
    Key("gcPist", Float(invalid="NaN", units="um")),
    Key("gcView", String()),
    Key("gFitChiSq", Float(invalid="NaN")),
    Key("gImCtr", Float(invalid="NaN"), Float(invalid="NaN")),
    Key("gImLim", Float(invalid="NaN"), Float(invalid="NaN"), Float(invalid="NaN"), Float(invalid="NaN")),
    Key("gImScale", Float(invalid="NaN"), Float(invalid="NaN")),
    Key("gPCentroid", Int(invalid="NaN")*(0,)),
    Key("gPCtr", Float(invalid="NaN"), Float(invalid="NaN")),
    Key("gPDisable", Int(invalid="NaN")*(0,)),
    Key("gPFindStar", Int(invalid="NaN")*(0,)),
    Key("gPLim", Float(invalid="NaN"), Float(invalid="NaN"), Float(invalid="NaN"), Float(invalid="NaN")),
    Key("gPNoStar", Int(invalid="NaN")*(0,)),
    Key("gPRotGImAng", Float(invalid="NaN")),
    Key("gPRotXY", Float(invalid="NaN"), Float(invalid="NaN")),
    Key("gProbe", Int(invalid="NaN")),
    Key("gResid", Float(invalid="NaN")),
    Key("gSDataPix", Float(invalid="NaN"), Float(invalid="NaN"), Float(invalid="NaN"), Float(invalid="NaN"),
        Float(invalid="NaN"), Float(invalid="NaN"), Float(invalid="NaN"), Float(invalid="NaN"),
        Int(invalid="NaN")),
    Key("gSMag", Float(invalid="NaN")),
    Key("gSName", String()),
    Key("gSPM", Float(invalid="NaN"), Float(invalid="NaN"), Float(invalid="NaN"), Float(invalid="NaN")),
    Key("gSPos", PVT(), PVT()),
    Key("gSSys", String(), Float(invalid="NaN")),
    Key("gSWavelength", Float(invalid="NaN")),
    Key("gScanSize", Float(invalid="NaN"), Float(invalid="NaN")),
    Key("gStats", Float(invalid="NaN"), Float(invalid="NaN"), Float(invalid="NaN"), Float(invalid="NaN"),
        Float(invalid="NaN"), Float(invalid="NaN")),
    Key("guideOff", PVT(), PVT(), PVT()),
    Key("guidePrep"),
    Key("guideStart"),
    Key("humidity", Float(invalid="NaN")),
    Key("iimCtr", Float(invalid="NaN", units="pixels")*2),
    Key("iimLim", Float(invalid="NaN", units="pixels")*4),
    Key("iimScale", Float(invalid="NaN", units="pixels/deg")*2),
    Key("inst", String()),
    Key("instPos", Enum("NA1", "NA2", "BC1", "TR1", "TR2", "SK1", "SK2", "SK3", "SK4", "CA1", "non")),
    Key("ipConfig", String()),
    Key("iter", UInt(invalid="NaN"), doCache=False),
    Key("job", String(), doCache=False),
    Key("lockInfo", String(), UInt(invalid="NaN")*2, String()*2, UInt(invalid="NaN"), String()*2, doCache=False),
    Key("lst", Float(invalid="NaN", units="deg")),
    Key("maxDuration", Float(invalid="NaN", units="s"), doCache=False),
    Key("maxIter", UInt(invalid="NaN"), doCache=False),
    Key("maxUsers", UInt(invalid="NaN")),
    Key("meas2PredErr", Float(invalid="NaN", units="as"), doCache=False),
    Key("modu", String(), doCache=False),
    Key("moveItems", String(), doCache=False),
    Key("moved"),
    Key("msgsLost", UInt(invalid="NaN"), doCache=False),
    Key("noEnd"),
    Key("noFacil"),
    Key("noRotOrScaleCorr"),
    Key("noStarsFound"),
    Key("noVMSMsg"),
    Key("notEnoughData"),
    Key("objArcOff", PVT(), PVT()),
    Key("objDist", Float(invalid="NaN", units="au")),
    Key("objInstAng", PVT()),
    Key("objMag", Float(invalid="NaN", units="mag")),
    Key("objName", String()),
    Key("objNetPos", PVT(), PVT()),
    Key("objOff", PVT(), PVT()),
    Key("objObs", PVT(), PVT()),
    Key("objPM", Float(invalid="NaN", units="as/century")*2, Float(invalid="NaN", units="as"),
        Float(invalid="NaN", units="km/s")),
    Key("objPos", PVT(), PVT()),
    Key("objSys", Enum("ICRS", "FK5", "FK4", "Gal", "Geo", "None", "Topo", "Obs", "Phys", "Mount", "Inst", "GImage"), Float(invalid="NaN")),
    Key("objWavelength", Float(invalid="NaN", units="A")),
    Key("objZPMPos", PVT(), PVT()),
    Key("predFWHM", Float(invalid="NaN", units="as"), doCache=False),
    Key("pressure", Float(invalid="NaN", units="Pa")),
    Key("primActMount", Float(invalid="NaN")*(1,)),
    Key("primCmdMount", Float(invalid="NaN")*(1,)),
    Key("primConstRMS", Float(invalid="NaN", units="um")),
    Key("primDesOrient", Float(invalid="NaN", units="um"), Float(invalid="NaN", units="as")*2,
        Float(invalid="NaN", units="um")*2),
    Key("primDesOrientAge", Float(invalid="NaN", units="s"), doCache=False),
    Key("primF_BFTemp", Float(invalid="NaN", units="deg")*2),
    Key("primOrient", Float(invalid="NaN", units="um"), Float(invalid="NaN", units="as")*2,
        Float(invalid="NaN", units="um")*2),
    Key("primStatus", UInt(invalid="NaN")*6),
    Key("ptRefPos", PVT(), PVT(), doCache=False),
    Key("ptRefRadius", Float(invalid="NaN", units="deg"), doCache=False),
    Key("ptScanSize", Float(invalid="NaN", units="deg"), doCache=False),
    Key("received", String(), doCache=False),
    Key("rejectedAxisErrCode", String(invalid="?")*3, doCache=False),
    Key("rotDTime", Float(invalid="NaN", units="s")),
    Key("rotErr", Float(invalid="NaN", units="as")*3, doCache=False),
    Key("rotID", UInt(invalid="NaN")*2),
    Key("rotLim", Float(invalid="NaN", units="deg")*2, Float(invalid="NaN", units="deg/s"),
        Float(invalid="NaN", units="deg/s^2"), Float(invalid="NaN", units="deg/s^3")),
    Key("rotMSStat", Float(invalid="NaN", units="as")*2, String()),
    Key("rotMount", PVT(), doCache=False),
    Key("rotPhys", PVT(), doCache=False),
    Key("rotPos", PVT()),
    Key("rotStat", Float(invalid="NaN", units="deg"), Float(invalid="NaN", units="deg/s"),
        Double(invalid="NaN", units="s"), UInt(invalid="NaN", reprFmt = '0x%x')),
    Key("rotType", Enum("None", "Obj", "Horiz", "Phys", "Mount")),
    Key("rotWrapPref", Enum("None", "Nearest", "Negative", "Middle", "Positive", "NoUnwrap"), doCache=False),
    Key("scaleFac", Float(invalid="NaN")),
    Key("scaleFacRange", Float(invalid="NaN")*2),
    Key("schMoveTimes", Float(invalid="NaN")*10, doCache=False),
    Key("secActMount", Float(invalid="NaN")*(1,)),
    Key("secCmdMount", Float(invalid="NaN")*(1,)),
    Key("secConstRMS", Float(invalid="NaN", units="um")),
    Key("secDesOrient", Float(invalid="NaN", units="um"), Float(invalid="NaN", units="as")*2,
        Float(invalid="NaN", units="um")*2),
    Key("secDesOrientAge", Float(invalid="NaN", units="s"), doCache=False),
    Key("secF_BFTemp", Float(invalid="NaN", units="deg")*2),
    Key("secFocus", Float(invalid="NaN", units="um")),
    Key("secOrient", Float(invalid="NaN", units="um"), Float(invalid="NaN", units="as")*2,
        Float(invalid="NaN", units="um")*2),
    Key("secStatus", UInt(invalid="NaN")*5),
    Key("secTrussTemp", Float(invalid="NaN", units="C"),
        help="Average temperature of the secondary truss elements. Used for automatic focus correction."
    ),
    Key("slewAdvTime", Float(invalid="NaN", units="s")),
    Key("slewBeg", Double(invalid="NaN", units="s"), doCache=False),
    Key("slewDuration", Float(invalid="NaN", units="s"), doCache=False),
    Key("slewEnd"),
    Key("slewSuperseded"),
    Key("spiderGImAng", PVT(), doCache=False),
    Key("spiderInstAng", PVT()),
    Key("stInterval", Float(invalid="NaN", units="s")*2, doCache=False),
    Key("started"),
    Key("superseded"),
    Key("tLapse", Float(invalid="NaN", units="C/km")),
    Key("tai", Double(invalid="NaN", units="s"), refreshCmd="show time"),
    Key("tccDTime", Float(invalid="NaN", units="s"), doCache=False),
    Key("tccPos", Float(invalid="NaN", units="deg", strFmt="%+07.2f")*3),
    Key("tccStatus", String()*2),
    Key("tdiCorr"),
    Key("telMount", PVT(), PVT(), doCache=False),
    Key("telPhys", PVT(), PVT(), doCache=False),
    Key("text", String(), doCache=False),
    Key("timeStamp", Double(invalid="NaN", units="s"), doCache=False),
    Key("trackAdvTime", Float(invalid="NaN", units="s"), doCache=False),
    Key("userAdded"),
    Key("userDeleted"),
    Key("userInfo", UInt(invalid="NaN"), UInt(invalid="NaN", reprFmt = '0x%x'),
        UInt(invalid="NaN"), Int(invalid="NaN"), UInt(invalid="NaN")*2),
    Key("userNum", UInt(invalid="NaN")),
    Key("ut1", Double(invalid="NaN", units="s")),
    Key("utc_TAI", Float(invalid="NaN", units="s")),
    Key("version", String()),
    Key("vmsMsg", String(), doCache=False),
    Key("warnAltStatus"),
    Key("warnAzStatus"),
    Key("warnRotStatus"),
    Key("windDir", Float(invalid="NaN", units="deg")),
    Key("windSpeed", Float(invalid="NaN", units="m/s")),
    Key("yourUserNum", UInt(invalid="NaN")),
)
