# Based on the TCC keywords documented at (with guide camera keywords omitted):
# http://www.apo.nmsu.edu/Telescopes/TCC/MessageKeywords.html

KeysDictionary('tcc', (3, 1), 
    Key('airTemp', Float(units='C'), help="Temperature of the outside air. Used for refraction correction."),
    Key('axePos', Float(units='deg', invalid='NaN', help="Order is Az, Alt, Rot")*3, help=
        """Actual mount position of azimuth, altitude and instrument rotator, as reported by
        the axes controllers. Not many digits past the decimal but very useful for status displays."""
    ), 
    Key('azAltDist', Float(), doCache=False), 
    Key('azDTime', Float(units='s')), 
    Key('altDTime', Float(units='s')), 
    Key('rotDTime', Float(units='s')), 
    Key('azErr', Float(units='as')*3, doCache=False), 
    Key('altErr', Float(units='as')*3, doCache=False), 
    Key('rotErr', Float(units='as')*3, doCache=False), 
    Key('azLim', Float(units='deg')*2, Float(units='deg/s'), Float(units='deg/s^2'), Float(units='deg/s^3')), 
    Key('altLim', Float(units='deg')*2, Float(units='deg/s'), Float(units='deg/s^2'), Float(units='deg/s^3')), 
    Key('rotLim', Float(units='deg')*2, Float(units='deg/s'), Float(units='deg/s^2'), Float(units='deg/s^3')), 
    Key('azMSStat', Float(units='as')*2, String()), 
    Key('altMSStat', Float(units='as')*2, String()), 
    Key('rotMSStat', Float(units='as')*2, String()), 
    Key('azPosRejected', Float(units='deg')*3, doCache=False), 
    Key('altPosRejected', Float(units='deg')*3, doCache=False), 
    Key('rotPosRejected', Float(units='deg')*3, doCache=False), 
    Key('azStat', Float(units='deg'), Float(units='deg/s'), Double(units='s'), Hex()), 
    Key('altStat', Float(units='deg'), Float(units='deg/s'), Double(units='s'), Hex()), 
    Key('rotStat', Float(units='deg'), Float(units='deg/s'), Double(units='s'), Hex()), 
    Key('axisBadStatusMask', Hex()), 
    Key('axisCmdState', Enum('Drifting', 'Halted', 'Halting', 'Slewing', 'Tracking', 'NotAvailable', invalid='?')*3), 
    Key('axisErrCode', String(invalid='?')*3), 
    Key('axisInit', String(), doCache=False), 
    Key('axisMaxDTime', Float(units='s'), doCache=False), 
    Key('axisNoSlew', String(), doCache=False), 
    Key('axisNoTrack', String(), doCache=False), 
    Key('axisStop', String(), doCache=False), 
    Key('axisWarnStatusMask', Hex()), 
    Key('azWrapPref', Enum('None', 'Near', 'Neg', 'Middle', 'Pos'), doCache=False), 
    Key('badCmd'), 
    Key('badAzStatus'), 
    Key('badAltStatus'), 
    Key('badRotStatus'), 
    Key('badAzDTime'), 
    Key('badAltDTime'), 
    Key('badRotDTime'), 
    Key('badUser', UInt(), doCache=False), 
    Key('blockInfo', String(), UInt()*2, doCache=False), 
    Key('boresight', Float(units='deg'), Float(units='deg/s'), Double(units='s'), Float(units='deg'), Float(units='deg/s'), Double(units='s')), 
    Key('broadcast', String(), doCache=False), 
    Key('calibOff', Float(units='deg'), Float(units='deg/s'), Double(units='s'), Float(units='deg'), Float(units='deg/s'), Double(units='s'), Float(units='deg'), Float(units='deg/s'), Double(units='s')), 
    Key('cmd', String(), doCache=False), 
    Key('cmdDTime', Float(units='s'), doCache=False), 
    Key('primConstRMS', Float(units='um')), 
    Key('secConstRMS', Float(units='um')), 
    Key('convAng', Float(units='deg'), Float(units='deg/s'), Double(units='s'), doCache=False), 
    Key('convPM', Float(units='as/century')*2, Float(units='as'), Float(units='km/s'), doCache=False), 
    Key('convPos', Float(units='deg'), Float(units='deg/s'), Double(units='s'), Float(units='deg'), Float(units='deg/s'), Double(units='s'), doCache=False), 
    Key('currArcOff', Float(units='deg'), Float(units='deg/s'), Double(units='s'), Float(units='deg'), Float(units='deg/s'), Double(units='s')), 
    Key('currUsers', UInt()), 
    Key('deadProc', String()*(1, ), doCache=False), 
    Key('disabledProc', String()*(1, ), doCache=False), 
    Key('duration', Float(units='s'), doCache=False), 
    Key('eText', String(), doCache=False), 
    Key('expected', String(), doCache=False), 
    Key('expTime', Float(units='s'), doCache=False), 
    Key('facil', String(), doCache=False), 
    Key('failed'), 
    Key('flushedFromBox', String(), doCache=False), 
    Key('humidity', Float()), 
    Key('iimCtr', Float(units='pixels')*2), 
    Key('iimLim', Float(units='pixels')*4), 
    Key('iimScale', Float(units='pixels/deg')*2), 
    Key('inst', String()), 
    Key('instPos', Enum('NA1', 'NA2', 'BC1', 'TR1', 'TR2', 'SK1', 'SK2', 'SK3', 'SK4', 'CA1', 'non')), 
    Key('ipConfig', String()), 
    Key('iter', UInt(), doCache=False), 
    Key('job', String(), doCache=False), 
    Key('lockInfo', String(), UInt()*2, String()*2, UInt(), String()*2, doCache=False), 
    Key('lst', Float(units='deg')), 
    Key('maxDuration', Float(units='s'), doCache=False), 
    Key('maxIter', UInt(), doCache=False), 
    Key('maxUsers', UInt()), 
    Key('meas2PredErr', Float(units='as'), doCache=False), 
    Key('primActMount', Float()*(1, )), 
    Key('secActMount', Float()*(1, )), 
    Key('mountActMount', Float()*(1, )), 
    Key('primCmdMount', Float()*(1, )), 
    Key('secCmdMount', Float()*(1, )), 
    Key('mountCmdMount', Float()*(1, )), 
    Key('primDesOrient', Float(units='um'), Float(units='as')*2, Float(units='um')*2), 
    Key('secDesOrient', Float(units='um'), Float(units='as')*2, Float(units='um')*2), 
    Key('primDesOrientAge', Float(units='s'), doCache=False), 
    Key('secDesOrientAge', Float(units='s'), doCache=False), 
    Key('primF_BFTemp', Float(units='deg')*2), 
    Key('secF_BFTemp', Float(units='deg')*2), 
    Key('primOrient', Float(units='um'), Float(units='as')*2, Float(units='um')*2), 
    Key('secOrient', Float(units='um'), Float(units='as')*2, Float(units='um')*2), 
    Key('primStat', String()*(1, )), 
    Key('secStat', String()*(1, )), 
    Key('mountStat', String()*(1, )), 
    Key('modu', String(), doCache=False), 
    Key('moved'), 
    Key('moveItems', String(), doCache=False), 
    Key('msgsLost', UInt(), doCache=False), 
    Key('noEnd'), 
    Key('noFacil'), 
    Key('noRotOrScaleCorr'), 
    Key('notEnoughData'), 
    Key('noVMSMsg'), 
    Key('objArcOff', Float(units='deg'), Float(units='deg/s'), Double(units='s'), Float(units='deg'), Float(units='deg/s'), Double(units='s')), 
    Key('objInstAng', Float(units='deg'), Float(units='deg/s'), Double(units='s')), 
    Key('objMag', Float(units='mag')), 
    Key('objName', String()), 
    Key('objNetPos', Float(units='deg'), Float(units='deg/s'), Double(units='s'), Float(units='deg'), Float(units='deg/s'), Double(units='s')), 
    Key('objOff', Float(units='deg'), Float(units='deg/s'), Double(units='s'), Float(units='deg'), Float(units='deg/s'), Double(units='s')), 
    Key('objPM', Float(units='as/century')*2, Float(units='as'), Float(units='km/s')), 
    Key('objPos', Float(units='deg'), Float(units='deg/s'), Double(units='s'), Float(units='deg'), Float(units='deg/s'), Double(units='s')), 
    Key('objSys', Enum('ICRS', 'FK5', 'FK4', 'Gal', 'Geo', 'None', 'Topo', 'Obs', 'Phys', 'Mount', 'Inst', 'GImage'), Float()), 
    Key('objWavelength', Float(units='A')), 
    Key('objZPMPos', Float(units='deg'), Float(units='deg/s'), Double(units='s'), Float(units='deg'), Float(units='deg/s'), Double(units='s')), 
    Key('predFWHM', Float(units='as'), doCache=False), 
    Key('pressure', Float(units='Pa')), 
    Key('ptRefPos', Float(units='deg'), Float(units='deg/s'), Double(units='s'), Float(units='deg'), Float(units='deg/s'), Double(units='s'), doCache=False), 
    Key('ptRefRadius', Float(units='deg'), doCache=False), 
    Key('ptScanSize', Float(units='deg'), doCache=False), 
    Key('received', String(), doCache=False), 
    Key('rejectedAxisErrCode', String(invalid='?')*3, doCache=False), 
    Key('rotID', UInt()*2), 
    Key('rotMount', Float(units='deg'), Float(units='deg/s'), Double(units='s'), doCache=False), 
    Key('rotPhys', Float(units='deg'), Float(units='deg/s'), Double(units='s'), doCache=False), 
    Key('rotPos', Float(units='deg'), Float(units='deg/s'), Double(units='s')), 
    Key('rotType', Enum('None', 'Obj', 'Horiz', 'Phys', 'Mount')), 
    Key('rotWrapPref', Enum('None', 'Near', 'Negative', 'Middle', 'Positive'), doCache=False), 
    Key('scaleFac', Float()), 
    Key('scaleFacRange', Float()*2), 
    Key('schMoveTimes', Float()*10, doCache=False), 
    Key('secFocus', Float(units='um')), 
    Key('secTrussTemp', Float(units='C'),
        help="Average temperature of the secondary truss elements. Used for automatic focus correction."
    ), 
    Key('slewAdvTime', Float(units='s')), 
    Key('slewBeg', Double(units='s'), doCache=False), 
    Key('slewDuration', Float(units='s'), doCache=False), 
    Key('slewEnd'), 
    Key('slewSuperseded'), 
    Key('spiderInstAng', Float(units='deg'), Float(units='deg/s'), Double(units='s')), 
    Key('started'), 
    Key('stInterval', Float(units='s')*2, doCache=False), 
    Key('superseded'), 
    Key('tai', Double(units='s'), refreshCmd="show time"), 
    Key('tccDTime', Float(units='s'), doCache=False), 
    Key('tccPos', Float(units='deg', invalid='NaN', strFmt='%+07.2f')*3), 
    Key('tccStatus', String()*2), 
    Key('tdiCorr'), 
    Key('telMount', Float(units='deg'), Float(units='deg/s'), Double(units='s'), Float(units='deg'), Float(units='deg/s'), Double(units='s'), doCache=False), 
    Key('telPhys', Float(units='deg'), Float(units='deg/s'), Double(units='s'), Float(units='deg'), Float(units='deg/s'), Double(units='s'), doCache=False), 
    Key('text', String(), doCache=False), 
    Key('timeStamp', Double(units='s'), doCache=False), 
    Key('tLapse', Float(units='C/km')), 
    Key('trackAdvTime', Float(units='s'), doCache=False), 
    Key('userAdded'), 
    Key('userDeleted'), 
    Key('userInfo', UInt(), Hex(), UInt(), Int(), UInt()*2), 
    Key('userNum', UInt()), 
    Key('ut1', Double(units='s')), 
    Key('utc_TAI', Float(units='s')), 
    Key('vmsMsg', String(), doCache=False), 
    Key('warnAzStatus'), 
    Key('warnAltStatus'), 
    Key('warnRotStatus'), 
    Key('windDir', Float(units='deg')), 
    Key('windSpeed', Float(units='m/s')), 
    Key('yourUserNum', UInt()), 
    # added for guide camera
    Key('guideOff', Float(units='deg'), Float(units='deg/s'), Double(units='s'), Float(units='deg'), Float(units='deg/s'), Double(units='s'), Float(units='deg'), Float(units='deg/s'), Double(units='s')), 
    Key('gCamCmd', String(), doCache=False), 
    Key('gcFocus', Float(units='um')), 
    Key('gcView', String()), 
    Key('gcNFilt', UInt()), 
    Key('gimScale', Float(units='pixels/deg')*2), 
    Key('gimCtr', Float(units='pixels')*2), 
    Key('gimLim', Float(units='pixels')*4), 
    # not yet in docs:
    Key('primStatus', UInt()*6), 
    Key('secStatus', UInt()*5), 
)
